### PR TITLE
Introduce PACKAGE_IGNORE_DEPS

### LINKED ISSUE #3: Installing dependencies
Many projects have at least one dependency beyond Emacs itself. I suggest adding a way to specify dependencies. I have been [doing that](https://github.com/mpdel/libmpdel/blob/master/Makefile#L18) [with Makefiles](https://github.com/mpdel/ivy-mpdel/blob/master/Makefile#L21) for some time [and others have too](https://github.com/magit/magit/blob/master/default.mk#L117).

### PR DESCRIPTION
**Pull request by vermiculus**
Fix #3.

### CODE REVIEW

**Comment by vermiculus** [comment]
@DamienCassou, can you give this a shot?

**Comment by DamienCassou** [comment]
I've started migrating mpdel to EMake: https://github.com/mpdel/mpdel/tree/emake. For now, it doesn't work because of package-lint and I don't know why.

**Comment by vermiculus** [comment]
I'm not sure how to see the test logs on gitlab's interface; are they available somewhere publicly?

**Comment by DamienCassou** [comment]
Sean Allred <notifications@github.com> writes:
> I'm not sure how to see the test logs on gitlab's interface; are they available somewhere publicly?


I have just created the PR:
https://gitlab.petton.fr/mpdel/mpdel/merge_requests/26. Click on
"Changes" to see what I have changed and "Pipelines" to see the CI.

-- 
Damien Cassou
http://damiencassou.seasidehosting.st

"Success is the ability to go from one failure to another without
losing enthusiasm." --Winston Churchill

**Comment by vermiculus** [comment]
Your makefile changed:

```
$ make ci-dependencies
make: *** No rule to make target 'ci-dependencies'.  Stop.
```

**Comment by vermiculus** [comment]
Opened a PR on mpdel that'll fix emake for you in this case. I tested with the appropriate changes and everything worked swimmingly, so I'm going to go ahead and merge this.

**Comment by vermiculus** [comment]
@DamienCassou Once you confirm, I'll tag and release 1.0.

Related to #16.

**Pull request merged**
