### PR TITLE
Make checkdoc and package-lint display the list of linted files

### PR DESCRIPTION
**Pull request by DamienCassou**

### CODE REVIEW

**Comment by vermiculus** [comment]
Isn't this the same as just looking at the `PACKAGE_LISP` variable, though?

**Comment by DamienCassou** [comment]
Sean Allred <notifications@github.com> writes:
> Isn't this the same as just looking at the `PACKAGE_LISP` variable,
> though?

The line of log you are referring to contains a lot of information and
is a bit cryptic: I see it as an implementation detail and that's why I
asked you to hide it with a `@`. Even if you know by heart that the
value of PACKAGE_LISP is a list of the files being checked, it might not
be the case of all EMake users when they look at their log (maybe 2
years after they installed and configured EMake). The message I'm asking
for would be clearer I think.

My opinion is that such a message would make the log say what EMake is
doing (running linting on a bunch of files) instead of how it does it
(by passing environment variables and launching a new Emacs instance).

-- 
Damien Cassou
http://damiencassou.seasidehosting.st

"Success is the ability to go from one failure to another without
losing enthusiasm." --Winston Churchill

**Comment by vermiculus** [comment]
Back in business 😄 

I have a bunch of patches on my machine that I've tinkered with over the past two weeks. Here is what running `make compile` on emake now looks like locally:

```
sh$ EMAKE_DEBUG_FLAGS="debug show-environment" make compile
PACKAGE_FILE="emake.el" PACKAGE_LISP="emake.el" PACKAGE_TESTS="" PACKAGE_ARCHIVES="gnu" PACKAGE_TEST_DEPS="" PACKAGE_TEST_ARCHIVES="gnu" emacs -batch -l emake.el --eval "(setq enable-dir-local-variables nil)"  --eval "(emake (pop argv))" install
emake: showing relevant environment information...
emake:     PACKAGE_ARCHIVES="gnu"
emake:       space-delimited list of named ELPA archives; see also `emake-package-archive-master-alist'
emake:     PACKAGE_FILE="emake.el"
emake:       root file of your package
emake: showing relevant environment information...done
emake: Running target "install" with function `emake-install'...
emake: No dependencies detected
emake: Running target "install" with function `emake-install'...done
rm -f emake.elc
PACKAGE_FILE="emake.el" PACKAGE_LISP="emake.el" PACKAGE_TESTS="" PACKAGE_ARCHIVES="gnu" PACKAGE_TEST_DEPS="" PACKAGE_TEST_ARCHIVES="gnu" emacs -batch -l emake.el --eval "(setq enable-dir-local-variables nil)"  --eval "(emake (pop argv))" compile ~error-on-warn
emake: showing relevant environment information...
emake:     PACKAGE_LISP="emake.el"
emake:       space-delimited list of Lisp files in this package
emake:       [target(compile)] these files are compiled
emake: showing relevant environment information...done
emake: Running target "compile" with function `emake-compile' with arguments ("~error-on-warn")...
emake: error-on-warn => t
emake: initializing package.el...
emake: initializing package.el...done
emake: compiling emake.el...
emake: compiling emake.el...done
emake: Running target "compile" with function `emake-compile' with arguments ("~error-on-warn")...done
```

Does this solve the same need? One advantage of this approach is that the `emacs` call could be thrown under `@` if desired.

I have to say I'm not a big fan of repeating ourselves. The documentation is pretty clear about which targets use which variables and how.

**Comment by vermiculus** [comment]
I've pushed the patches discussed above.

**Comment by DamienCassou** [comment]
Thanks for your work. I'm closing this PR.

**Pull request closed without merging**
